services:
  - name: streamlit
    buildCommand: pip install -r src/requirements.txt
    startCommand: streamlit run src/app.py

  - name: fastapi
    buildCommand: pip install -r src/requirements.txt
    startCommand: uvicorn src.main:app --host=0.0.0.0 --port=8080
