services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.main:app --host=0.0.0.0 --port=$PORT"
    plan: free
    port: $PORT

  - type: web
    name: frontend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run src/app.py --server.port=$PORT"
    plan: free
    port: $PORT
