services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.main:app --host=0.0.0.0 --port=8080"
    plan: free
    port: 8080
  - type: web
    name: frontend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run src/app.py --server.port 8501"
    plan: free
    port: 8501
