services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install --no-cache-dir -r requirements-web.txt"
    startCommand: "uvicorn src.main:app --host=0.0.0.0 --port=${PORT}"
    plan: free

  - type: web
    name: frontend
    env: python
    buildCommand: "pip install --no-cache-dir -r requirements-web.txt"
    startCommand: "streamlit run src/app.py --server.port=${PORT} --server.address=0.0.0.0"
    plan: free
