# examples.yaml
# A list of placeholder prompts we’ll cycle through:

- "Where can I dance salsa tonight?"
- "When is the next bachata social in Victoria?"
- "Show me West Coast Swing events this Saturday."
- "Find salsa lessons near me this month."
