"""
Chatbot Batch Testing Module

Generates test questions, executes them through the chatbot, and prepares
manual-review artifacts.

This module contains three main components:
1. TestQuestionGenerator - Generates questions from templates
2. ChatbotTestExecutor - Executes questions through chatbot pipeline
3. generate_chatbot_report() - Creates comprehensive reports from raw execution data

Author: Claude Code
Version: 1.0.0
"""

from datetime import datetime
from datetime import timedelta
from itertools import product
import json
import logging
import numpy as np
import os
import pandas as pd
import re
import random
import sys
import time
from typing import Dict, List, Optional
from zoneinfo import ZoneInfo
import yaml

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../../src'))

from output_paths import chatbot_path, reports_path


class TestQuestionGenerator:
    """
    Generates test questions from YAML templates.

    Supports two question types:
    - Template-based: Questions generated by combining parameters
    - Static: Pre-written natural language questions

    Attributes:
        template_file (str): Path to YAML template file
        templates (dict): Loaded template configuration
    """

    def __init__(self, template_file: str = 'tests/data/chatbot_test_questions.yaml'):
        """
        Initialize the TestQuestionGenerator.

        Args:
            template_file (str): Path to YAML file with question templates
        """
        self.template_file = template_file

        # Load templates
        if not os.path.exists(template_file):
            raise FileNotFoundError(f"Template file not found: {template_file}")

        with open(template_file, 'r') as f:
            self.templates = yaml.safe_load(f)

        logging.info(f"Loaded question templates from: {template_file}")

    def generate_all_questions(self) -> List[dict]:
        """
        Generate all test questions from templates.

        Returns:
            List[dict]: List of question dictionaries with keys:
                - question (str): The question text
                - category (str): Question category
                - parameters (dict): Template parameters (for template-based)
                - expected_criteria (dict): Expected criteria for scoring
        """
        questions = []

        for template_config in self.templates['templates']:
            category = template_config['category']

            if 'static_questions' in template_config:
                # Static questions (natural language)
                for question_text in template_config['static_questions']:
                    questions.append({
                        'question': question_text,
                        'category': category,
                        'expected_criteria': self._extract_criteria(question_text)
                    })
            else:
                # Template-based generation
                questions.extend(self._generate_from_template(template_config))

        logging.info(f"Generated {len(questions)} test questions across {len(self.templates['templates'])} categories")
        return questions

    def _generate_from_template(self, config: dict) -> List[dict]:
        """
        Generate questions by combining template parameters.

        Args:
            config (dict): Template configuration with template string and parameters

        Returns:
            List[dict]: Generated question dictionaries
        """
        template = config['template']
        param_names = list(config['parameters'].keys())
        param_values = [config['parameters'][name] for name in param_names]

        questions = []

        # Generate all combinations using itertools.product
        for combo in product(*param_values):
            params = dict(zip(param_names, combo))
            question_text = template.format(**params)

            questions.append({
                'question': question_text,
                'category': config['category'],
                'parameters': params,
                'expected_criteria': params  # Parameters ARE the expected criteria
            })

        return questions

    def _extract_criteria(self, question: str) -> dict:
        """
        Extract expected criteria from natural language question.

        Uses keyword matching to identify dance styles, event types, and timeframes.

        Args:
            question (str): Natural language question

        Returns:
            dict: Extracted criteria (dance_style, event_type, timeframe)
        """
        criteria = {}

        # Dance styles (extended list)
        styles = [
            'salsa', 'bachata', 'tango', 'west coast swing', 'wcs',
            'kizomba', 'zouk', 'lindy hop', 'balboa', 'swing'
        ]
        for style in styles:
            if style.lower() in question.lower():
                criteria['dance_style'] = style
                break

        # Event types
        if any(word in question.lower() for word in ['class', 'learn', 'beginner']):
            criteria['event_type'] = 'class'
        elif 'social' in question.lower():
            criteria['event_type'] = 'social dance'
        elif 'workshop' in question.lower():
            criteria['event_type'] = 'workshop'

        # Timeframes
        if 'tonight' in question.lower():
            criteria['timeframe'] = 'tonight'
        elif 'weekend' in question.lower():
            criteria['timeframe'] = 'this weekend'
        elif 'week' in question.lower():
            criteria['timeframe'] = 'this week'

        return criteria


class ChatbotTestExecutor:
    """
    Executes test questions through the chatbot pipeline.

    Uses the actual chatbot prompt and SQL generation logic to ensure
    tests reflect real production behavior.

    Attributes:
        config (dict): Configuration dictionary
        db_handler: DatabaseHandler instance
        llm_handler: LLMHandler instance
        sql_prompt_template (str): Loaded SQL generation prompt
    """

    def __init__(self, config: dict, db_handler):
        """
        Initialize the ChatbotTestExecutor.

        Args:
            config (dict): Configuration dictionary
            db_handler: DatabaseHandler instance
        """
        self.config = config
        self.db_handler = db_handler

        # Import LLMHandler
        import sys
        sys.path.insert(0, 'src')
        from llm import LLMHandler

        self.llm_handler = LLMHandler(config_path='config/config.yaml')

        # Load actual chatbot SQL prompt (path from config if provided)
        prompt_path = (
            self.config.get('prompts', {})
                .get('contextual_sql', {})
                .get('file', 'prompts/contextual_sql_prompt.txt')
        )
        if not os.path.exists(prompt_path):
            raise FileNotFoundError(f"SQL prompt file not found: {prompt_path}")

        with open(prompt_path, 'r') as f:
            self.sql_prompt_template = f.read()

        # Load interpretation prompt (for confirmation text generation)
        interpretation_prompt_path = (
            self.config.get('prompts', {})
                .get('interpretation', {})
                .get('file', 'prompts/interpretation_prompt.txt')
        )
        if not os.path.exists(interpretation_prompt_path):
            raise FileNotFoundError(f"Interpretation prompt file not found: {interpretation_prompt_path}")

        with open(interpretation_prompt_path, 'r') as f:
            self.interpretation_prompt_template = f.read()

        logging.info("ChatbotTestExecutor initialized with production prompts")

    @staticmethod
    def _sql_has_illegal_date_arithmetic(sql: str) -> bool:
        if not sql:
            return False
        s = sql.upper()
        patterns = [
            r"\bCURRENT_DATE\s*[\+\-]\s*\d+\b",
            r"\bCURRENT_TIMESTAMP\s*[\+\-]\s*\d+\b",
            r"'\d{4}-\d{2}-\d{2}'\s*[\+\-]",
        ]
        return any(re.search(p, s) for p in patterns)

    def generate_interpretation(self, user_query: str, current_date: str, current_day_of_week: str, current_time: str) -> str:
        """
        Generate a natural language interpretation of the user's search intent.
        This mirrors the generate_interpretation() function in main.py.

        Args:
            user_query: The user's input query
            current_date: Current date in YYYY-MM-DD format
            current_day_of_week: Current day name (e.g., "Monday")
            current_time: Current time with timezone (e.g., "14:30 PST")

        Returns:
            str: Natural language interpretation of the search intent
        """
        default_city = self.config.get('location', {}).get('epicentre', 'Victoria, British Columbia, Canada')

        # Format the interpretation prompt
        formatted_prompt = self.interpretation_prompt_template.format(
            current_date=current_date,
            current_day_of_week=current_day_of_week,
            current_time=current_time,
            default_city=default_city,
            user_query=user_query
        )

        try:
            # Query LLM for interpretation WITH date calculator tool
            from date_calculator import CALCULATE_DATE_RANGE_TOOL
            interpretation = self.llm_handler.query_llm('', formatted_prompt, tools=[CALCULATE_DATE_RANGE_TOOL])

            if not interpretation:
                return f"My understanding is that you want to search for dance events related to: {user_query}"

            return interpretation.strip()

        except Exception as e:
            logging.error(f"Error generating interpretation: {e}")
            return f"My understanding is that you want to search for: {user_query}"

    def _build_sql_prompt(
        self,
        question_dict: dict,
        current_date: str,
        current_day_of_week: str,
        current_question: str,
        conversation_history: str = "",
    ) -> str:
        """Build SQL-generation prompt with optional synthetic clarification history."""
        prompt = self.sql_prompt_template.format(
            context_info="",
            conversation_history=conversation_history,
            intent="search",
            entities=str(question_dict.get('parameters', {})),
            current_date=current_date,
            current_day_of_week=current_day_of_week
        )
        prompt += f"\n\nCurrent User Question: \"{current_question}\""
        return prompt

    @staticmethod
    def _column_reply_options() -> dict[str, list[str]]:
        """Natural clarification snippets mapped to query columns/filters."""
        return {
            "dance_style": [
                "Salsa and bachata.",
                "West coast swing.",
                "Tango only.",
                "Any partner dance style.",
            ],
            "event_type": [
                "Social dances only.",
                "Classes and socials.",
                "Workshops only.",
                "Live music dance events.",
            ],
            "timeframe": [
                "This weekend.",
                "Next week.",
                "Tomorrow night.",
                "First week of next month.",
            ],
            "location": [
                "In Victoria.",
                "Downtown Victoria.",
                "Anywhere in Greater Victoria.",
                "Victoria or Sidney.",
            ],
            "price": [
                "Free events only.",
                "Paid is fine too.",
                "Under $30 if possible.",
                "No price preference.",
            ],
        }

    @staticmethod
    def _infer_clarification_column(clarification_text: str) -> str:
        """Infer likely filter column from assistant clarification text."""
        low = str(clarification_text or "").lower()
        if any(t in low for t in ("style", "dance style", "salsa", "bachata", "tango", "swing")):
            return "dance_style"
        if any(t in low for t in ("event type", "class", "social", "workshop", "live music")):
            return "event_type"
        if any(t in low for t in ("date", "when", "timeframe", "week", "weekend", "day", "tonight", "tomorrow")):
            return "timeframe"
        if any(t in low for t in ("location", "city", "where", "venue", "area", "victoria", "sidney")):
            return "location"
        if any(t in low for t in ("price", "cost", "free", "budget", "$", "dollar")):
            return "price"
        return "timeframe"

    def _generate_column_based_clarification_reply(
        self,
        clarification_text: str,
        used_columns: set[str],
    ) -> tuple[str, str]:
        """
        Generate natural follow-up by adding one unresolved filter dimension.
        Returns (reply_text, column_name).
        """
        options_by_col = self._column_reply_options()
        inferred = self._infer_clarification_column(clarification_text)
        ordered_cols = [inferred] + [c for c in options_by_col if c != inferred]
        chosen_col = next((c for c in ordered_cols if c not in used_columns), inferred)
        replies = options_by_col.get(chosen_col, options_by_col["timeframe"])
        reply_text = random.choice(replies)
        return reply_text, chosen_col

    def execute_test_question(self, question_dict: dict) -> dict:
        """
        Execute a single test question through full chatbot pipeline.

        Steps:
        1. Format prompt with current date/time context
        2. Query LLM for SQL generation
        3. Sanitize SQL (same logic as main.py)
        4. Execute SQL and capture results

        Args:
            question_dict (dict): Question dictionary from TestQuestionGenerator

        Returns:
            dict: Test result with SQL, results, execution status
        """
        question = question_dict['question']

        # Get current date context (Pacific timezone - same as chatbot)
        pacific_tz = ZoneInfo("America/Los_Angeles")
        now = datetime.now(pacific_tz)
        current_date = now.strftime("%Y-%m-%d")
        current_day_of_week = now.strftime("%A")
        current_time = now.strftime("%H:%M %Z")

        # STEP 1: Generate interpretation (confirmation text)
        interpretation = self.generate_interpretation(
            user_query=question,
            current_date=current_date,
            current_day_of_week=current_day_of_week,
            current_time=current_time
        )

        try:
            # Import date calculator tool
            from date_calculator import CALCULATE_DATE_RANGE_TOOL

            chatbot_cfg = (
                self.config.get('testing', {})
                .get('validation', {})
                .get('chatbot', {})
            )
            min_depth = int(chatbot_cfg.get("clarification_min_depth", 1) or 1)
            max_depth = int(chatbot_cfg.get("clarification_max_depth", 3) or 3)
            if max_depth < min_depth:
                max_depth = min_depth
            target_depth = random.randint(min_depth, max_depth)
            max_turns = int(chatbot_cfg.get("max_clarification_turns", max(4, max_depth + 1)) or max(4, max_depth + 1))

            clarification_chain: list[dict] = []
            conversation_lines: list[str] = []
            current_question = question
            sql_raw = None
            turns_executed = 0
            used_columns: set[str] = set()

            # Multi-turn clarification drill: if clarification occurs, continue with synthetic follow-up responses.
            for turn_idx in range(1, max_turns + 1):
                turns_executed = turn_idx
                conversation_history = "\n".join(conversation_lines)
                prompt = self._build_sql_prompt(
                    question_dict=question_dict,
                    current_date=current_date,
                    current_day_of_week=current_day_of_week,
                    current_question=current_question,
                    conversation_history=conversation_history,
                )
                sql_raw = self.llm_handler.query_llm('', prompt, tools=[CALCULATE_DATE_RANGE_TOOL])
                if not sql_raw:
                    return self._create_error_result(question_dict, "LLM returned empty response")

                stripped = sql_raw.strip()
                if not stripped.startswith("CLARIFICATION:"):
                    break

                clarification_text = stripped.replace("CLARIFICATION:", "").strip()
                chain_row = {
                    "turn": turn_idx,
                    "clarification_text": clarification_text,
                }
                clarification_chain.append(chain_row)
                logging.info("QUESTION: %s", question)
                logging.info(
                    "CLARIFICATION TURN %s/%s (target_depth=%s): %s",
                    turn_idx,
                    max_turns,
                    target_depth,
                    clarification_text,
                )

                if len(clarification_chain) >= target_depth and turn_idx >= target_depth:
                    # Depth target met; keep the clarification result visible for scoring/diagnostics.
                    break

                user_reply, clarified_column = self._generate_column_based_clarification_reply(
                    clarification_text=clarification_text,
                    used_columns=used_columns,
                )
                used_columns.add(clarified_column)
                chain_row["synthetic_user_reply"] = user_reply
                chain_row["clarified_column"] = clarified_column
                conversation_lines.append(f"User: {current_question}")
                conversation_lines.append(f"Assistant: {clarification_text}")
                conversation_lines.append(f"User Clarification: {user_reply}")
                current_question = user_reply

            if not sql_raw:
                return self._create_error_result(question_dict, "LLM returned empty response")

            # CLARIFICATION path
            if sql_raw.strip().startswith("CLARIFICATION:"):
                clarification_text = sql_raw.strip().replace("CLARIFICATION:", "").strip()
                logging.info("QUESTION: %s", question)
                logging.info("CLARIFICATION TEXT: %s", clarification_text)
                return {
                    'question': question,
                    'category': question_dict['category'],
                    'expected_criteria': question_dict.get('expected_criteria', {}),
                    'interpretation': interpretation,
                    'sql_query': sql_raw.strip(),
                    'clarification_text': clarification_text,
                    'sql_syntax_valid': True,
                    'execution_success': True,
                    'result_count': 0,
                    'sample_results': [],
                    'timestamp': datetime.now().isoformat(),
                    'current_date_used': current_date,
                    'current_timezone': "America/Los_Angeles",
                    'is_clarification': True,
                    'clarification_depth_target': target_depth,
                    'clarification_depth_achieved': len(clarification_chain) if clarification_chain else 1,
                    'clarification_chain': clarification_chain or [{"turn": 1, "clarification_text": clarification_text}],
                    'clarification_turns_executed': turns_executed,
                }

            # Sanitize SQL
            sql_query = sql_raw.replace("```sql", "").replace("```", "").strip()
            select_idx = sql_query.upper().find("SELECT")
            if select_idx != -1:
                sql_query = sql_query[select_idx:]
            sql_query = sql_query.split(";")[0].strip()

            # Preflight re-query if illegal date arithmetic is detected
            if self._sql_has_illegal_date_arithmetic(sql_query):
                strict_suffix = (
                    "\n\nSTRICT FIX: You MUST call calculate_date_range for ANY temporal expression and use ONLY the returned dates. "
                    "Never add/subtract integers to dates (e.g., CURRENT_DATE + 7). If referencing CURRENT_DATE, use INTERVAL syntax only, "
                    "but prefer explicit dates from the tool. Return ONLY SQL."
                )
                strict_history = "\n".join(conversation_lines)
                strict_base_prompt = self._build_sql_prompt(
                    question_dict,
                    current_date,
                    current_day_of_week,
                    current_question,
                    strict_history,
                )
                strict_prompt = f"{strict_base_prompt}\n{strict_suffix}"
                sql_raw2 = self.llm_handler.query_llm('', strict_prompt, tools=[CALCULATE_DATE_RANGE_TOOL])
                if sql_raw2:
                    sql2 = sql_raw2.replace("```sql", "").replace("```", "").strip()
                    si2 = sql2.upper().find("SELECT")
                    if si2 != -1:
                        sql2 = sql2[si2:]
                    sql2 = sql2.split(";")[0].strip()
                    if not self._sql_has_illegal_date_arithmetic(sql2):
                        sql_query = sql2

            # Log the final SQL that will be validated/executed
            logging.info("QUESTION: %s", question)
            logging.info("SQL:\n%s", sql_query or "<none>")

            # Validate SQL syntax
            syntax_valid = self._check_sql_syntax(sql_query)
            if not syntax_valid and self._sql_has_illegal_date_arithmetic(sql_query):
                logging.warning("Preflight: Invalid SQL with illegal date arithmetic detected. Attempting re-query.")

            # Execute query if valid
            if syntax_valid:
                try:
                    results = self.db_handler.execute_query(sql_query)
                    execution_success = True
                    result_count = len(results) if results else 0

                    # Get sample results (first 5)
                    if results:
                        sample_results = [dict(row._mapping) for row in results[:5]]
                    else:
                        sample_results = []

                except Exception as e:
                    logging.error(f"SQL execution failed for question '{question}': {e}")
                    execution_success = False
                    result_count = 0
                    sample_results = []
            else:
                execution_success = False
                result_count = 0
                sample_results = []

            return {
                'question': question,
                'category': question_dict['category'],
                'expected_criteria': question_dict.get('expected_criteria', {}),
                'interpretation': interpretation,
                'sql_query': sql_query,
                'sql_syntax_valid': syntax_valid,
                'execution_success': execution_success,
                'result_count': result_count,
                'sample_results': sample_results,
                'timestamp': datetime.now().isoformat(),
                'current_date_used': current_date,
                'current_timezone': "America/Los_Angeles",
                'clarification_depth_target': target_depth,
                'clarification_depth_achieved': len(clarification_chain),
                'clarification_chain': clarification_chain,
                'clarification_turns_executed': turns_executed,
            }

        except Exception as e:
            logging.error(f"Test execution failed for question '{question}': {e}")
            return self._create_error_result(question_dict, str(e))

    def _check_sql_syntax(self, sql_query: str) -> bool:
        """
        Basic SQL validation.

        Checks for:
        - SELECT keyword presence
        - FROM events clause
        - Basic SQL structure

        Args:
            sql_query (str): SQL query string

        Returns:
            bool: True if syntax appears valid
        """
        if not sql_query:
            return False

        sql_upper = sql_query.upper()

        # Must contain SELECT
        if 'SELECT' not in sql_upper:
            return False

        # Must query events table (handle multiline SQL with extra whitespace)
        import re
        if not re.search(r'FROM\s+EVENTS', sql_upper):
            return False

        # Try to parse with sqlalchemy (basic validation)
        try:
            from sqlalchemy import text
            text(sql_query)
            return True
        except Exception as e:
            logging.warning(f"SQL parsing failed: {e}")
            return False

    def _create_error_result(self, question_dict: dict, error_message: str) -> dict:
        """Helper to create error result dictionary."""
        return {
            'question': question_dict['question'],
            'category': question_dict['category'],
            'expected_criteria': question_dict.get('expected_criteria', {}),
            'sql_query': None,
            'sql_syntax_valid': False,
            'execution_success': False,
            'result_count': 0,
            'sample_results': [],
            'error': error_message,
            'timestamp': datetime.now().isoformat()
        }

    def execute_all_tests(self, questions: List[dict]) -> List[dict]:
        """
        Execute all test questions.

        Args:
            questions (List[dict]): List of question dictionaries

        Returns:
            List[dict]: List of test results
        """
        results = []
        total = len(questions)

        logging.info(f"Executing {total} test questions...")

        for i, question_dict in enumerate(questions, 1):
            logging.info(f"Executing test {i}/{total}: {question_dict['question'][:60]}...")

            result = self.execute_test_question(question_dict)
            results.append(result)

            # Small delay to avoid API rate limits
            time.sleep(0.5)

        logging.info(f"Completed {len(results)} test executions")
        return results


def generate_chatbot_report(test_results: List[dict], output_dir: str = 'output') -> dict:
    """
    Generate comprehensive chatbot testing report.

    Creates:
    - CSV with all results
    - JSON with summary + analysis

    Args:
        test_results (List[dict]): Raw chatbot test results
        output_dir (str): Output directory path

    Returns:
        dict: Report dictionary
    """
    os.makedirs(output_dir, exist_ok=True)

    # Save detailed results to CSV
    try:
            # Flatten evaluation dict for CSV
        flattened_results = []
        for result in test_results:
            flat = result.copy()
            # Remove complex fields for CSV
            flat.pop('sample_results', None)
            flat.pop('expected_criteria', None)
            flat.pop('parameters', None)

            flattened_results.append(flat)

        results_df = pd.DataFrame(flattened_results)
        csv_path = chatbot_path('chatbot_test_results.csv')
        results_df.to_csv(csv_path, index=False)
        logging.info(f"CSV results saved: {csv_path}")

    except Exception as e:
        logging.error(f"Failed to save CSV: {e}")

    # Calculate summary statistics
    total_tests = len(test_results)
    execution_success_count = sum(1 for r in test_results if r['execution_success'])
    execution_success_rate = execution_success_count / total_tests if total_tests > 0 else 0

    # Category breakdown
    categories = set(r['category'] for r in test_results)
    category_stats = {}

    for category in categories:
        cat_results = [r for r in test_results if r['category'] == category]
        cat_success = sum(1 for r in cat_results if r['execution_success'])

        category_stats[category] = {
            'count': len(cat_results),
            'success_rate': cat_success / len(cat_results) if cat_results else 0
        }

    report = {
        'timestamp': datetime.now().isoformat(),
        'summary': {
            'total_tests': total_tests,
            'execution_success_rate': float(execution_success_rate),
            'average_score': None,
            'score_distribution': {'pending_human_review': total_tests},
            'interpretation_evaluation': {},
        },
        'category_breakdown': category_stats,
        'review_rows': [
            {
                'question': r.get('question', ''),
                'category': r.get('category', ''),
                'interpretation': r.get('interpretation', ''),
                'sql_query': r.get('sql_query', 'N/A'),
                'score': '',
                'reasoning': '',
                'criteria_matched': [],
                'criteria_missed': [],
                'sql_issues': [],
                'interpretation_score': '',
                'interpretation_issues': [],
                'execution_success': bool(r.get('execution_success', False)),
                'result_count': int(r.get('result_count', 0) or 0),
                'error': str(r.get('error', '') or ''),
                'is_clarification': bool(r.get('is_clarification', False)),
                'clarification_text': str(r.get('clarification_text', '') or ''),
            }
            for r in test_results
        ],
        'problematic_questions': [],
        'problem_categories': [],
        'problem_category_regression_cases': [],
        'failed_interpretations': [],
        'recommendations': [
            {
                'issue': 'Human chatbot review required',
                'occurrences': total_tests,
                'recommendation': 'Score chatbot_evaluation_review.csv before the next pipeline run to establish chatbot correctness.',
            }
        ] if total_tests > 0 else [],
    }

    # Save JSON report
    try:
        json_path = reports_path('chatbot_evaluation_report.json')
        with open(json_path, 'w') as f:
            json.dump(report, f, indent=2)
        logging.info(f"JSON report saved: {json_path}")
    except Exception as e:
        logging.error(f"Failed to save JSON report: {e}")

    return report
