import json
import pandas as pd

string = """
[
    {
        "org_name": "",
        "dance_style": "",
        "url": "",
        "event_type": "other",
        "event_name": "Studio closed for the holidays",
        "day_of_week": "",
        "start_date": "2024-12-23",
        "end_date": "2025-01-05",
        "start_time": "",
        "end_time": "",
        "price": "",
        "location": "",
        "description": "Studio closed for the holidays"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Ladies Team",
        "day_of_week": "Monday",
        "start_date": "2025-01-06",
        "end_date": "2025-01-06",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Ladies Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Salsa On 2 & Cha Cha Cha - Intermediate/ Advanced",
        "day_of_week": "Monday",
        "start_date": "2025-01-06",
        "end_date": "2025-01-06",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Salsa On 2 & Cha Cha Cha - Intermediate/ Advanced"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Touring & Training Team",
        "day_of_week": "Monday",
        "start_date": "2025-01-06",
        "end_date": "2025-01-06",
        "start_time": "21:00",
        "end_time": "22:30",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Touring & Training Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Student Salsa Team",
        "day_of_week": "Tuesday",
        "start_date": "2025-01-07",
        "end_date": "2025-01-07",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Student Salsa Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Salsa On 2 & Cha Cha- Fundamentals",
        "day_of_week": "Tuesday",
        "start_date": "2025-01-07",
        "end_date": "2025-01-07",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Salsa On 2 & Cha Cha- Fundamentals"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Salsa On 2 & Cha Cha- Beginner Intermediate",
        "day_of_week": "Tuesday",
        "start_date": "2025-01-07",
        "end_date": "2025-01-07",
        "start_time": "21:00",
        "end_time": "22:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Salsa On 2 & Cha Cha- Beginner Intermediate"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Ladies Team",
        "day_of_week": "Wednesday",
        "start_date": "2025-01-08",
        "end_date": "2025-01-08",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Ladies Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Company Class",
        "day_of_week": "Wednesday",
        "start_date": "2025-01-08",
        "end_date": "2025-01-08",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Company Class"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Touring & Training Team",
        "day_of_week": "Wednesday",
        "start_date": "2025-01-08",
        "end_date": "2025-01-08",
        "start_time": "21:00",
        "end_time": "22:30",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Touring & Training Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "bachata, merengue",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Bachata Team",
        "day_of_week": "Thursday",
        "start_date": "2025-01-09",
        "end_date": "2025-01-09",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Bachata Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "bachata, merengue",
        "url": "",
        "event_type": "class",
        "event_name": "Bachata & Merengue- All Levels",
        "day_of_week": "Thursday",
        "start_date": "2025-01-09",
        "end_date": "2025-01-09",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Bachata & Merengue- All Levels"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "social dance",
        "event_name": "Student Social & Practice Time",
        "day_of_week": "Thursday",
        "start_date": "2025-01-09",
        "end_date": "2025-01-09",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Student Social & Practice Time"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "social dance",
        "event_name": "Party- Caliente Salsa Saturdays",
        "day_of_week": "Saturday",
        "start_date": "2025-01-11",
        "end_date": "2025-01-12",
        "start_time": "20:15",
        "end_time": "00:00",
        "price": "",
        "location": "STUDIO 4 ATHLETICS, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Party- Caliente Salsa Saturdays"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Ladies Team",
        "day_of_week": "Monday",
        "start_date": "2025-01-13",
        "end_date": "2025-01-13",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Ladies Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Salsa On 2 & Cha Cha Cha - Intermediate/ Advanced",
        "day_of_week": "Monday",
        "start_date": "2025-01-13",
        "end_date": "2025-01-13",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Salsa On 2 & Cha Cha Cha - Intermediate/ Advanced"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Touring & Training Team",
        "day_of_week": "Monday",
        "start_date": "2025-01-13",
        "end_date": "2025-01-13",
        "start_time": "21:00",
        "end_time": "22:30",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Touring & Training Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Student Salsa Team",
        "day_of_week": "Tuesday",
        "start_date": "2025-01-14",
        "end_date": "2025-01-14",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Student Salsa Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Salsa On 2 & Cha Cha- Fundamentals",
        "day_of_week": "Tuesday",
        "start_date": "2025-01-14",
        "end_date": "2025-01-14",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Salsa On 2 & Cha Cha- Fundamentals"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Salsa On 2 & Cha Cha- Beginner Intermediate",
        "day_of_week": "Tuesday",
        "start_date": "2025-01-14",
        "end_date": "2025-01-14",
        "start_time": "21:00",
        "end_time": "22:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Salsa On 2 & Cha Cha- Beginner Intermediate"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Ladies Team",
        "day_of_week": "Wednesday",
        "start_date": "2025-01-15",
        "end_date": "2025-01-15",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Ladies Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Company Class",
        "day_of_week": "Wednesday",
        "start_date": "2025-01-15",
        "end_date": "2025-01-15",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Company Class"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Touring & Training Team",
        "day_of_week": "Wednesday",
        "start_date": "2025-01-15",
        "end_date": "2025-01-15",
        "start_time": "21:00",
        "end_time": "22:30",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Touring & Training Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "bachata, merengue",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Bachata Team",
        "day_of_week": "Thursday",
        "start_date": "2025-01-16",
        "end_date": "2025-01-16",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Bachata Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "bachata, merengue",
        "url": "",
        "event_type": "class",
        "event_name": "Bachata & Merengue- All Levels",
        "day_of_week": "Thursday",
        "start_date": "2025-01-16",
        "end_date": "2025-01-16",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Bachata & Merengue- All Levels"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "social dance",
        "event_name": "Student Social & Practice Time",
        "day_of_week": "Thursday",
        "start_date": "2025-01-16",
        "end_date": "2025-01-16",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Student Social & Practice Time"
    },
    {
        "org_name": "Dance City",
        "dance_style": "salsa",
        "url": "",
        "event_type": "social dance",
        "event_name": "Party- Salsa Night @ Dance City",
        "day_of_week": "Friday",
        "start_date": "2025-01-24",
        "end_date": "2025-01-25",
        "start_time": "20:15",
        "end_time": "00:00",
        "price": "",
        "location": "Victoria Edelweiss Club, 108 Niagara St, Victoria, BC V8V 1E9, Canada",
        "description": "Party- Salsa Night @ Dance City"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Ladies Team",
        "day_of_week": "Monday",
        "start_date": "2025-01-27",
        "end_date": "2025-01-27",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Ladies Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Salsa On 2 & Cha Cha Cha - Intermediate/ Advanced",
        "day_of_week": "Monday",
        "start_date": "2025-01-27",
        "end_date": "2025-01-27",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Salsa On 2 & Cha Cha Cha - Intermediate/ Advanced"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Touring & Training Team",
        "day_of_week": "Monday",
        "start_date": "2025-01-27",
        "end_date": "2025-01-27",
        "start_time": "21:00",
        "end_time": "22:30",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Touring & Training Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Student Salsa Team",
        "day_of_week": "Tuesday",
        "start_date": "2025-01-28",
        "end_date": "2025-01-28",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Student Salsa Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Salsa On 2 & Cha Cha- Fundamentals",
        "day_of_week": "Tuesday",
        "start_date": "2025-01-28",
        "end_date": "2025-01-28",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Salsa On 2 & Cha Cha- Fundamentals"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Salsa On 2 & Cha Cha- Beginner Intermediate",
        "day_of_week": "Tuesday",
        "start_date": "2025-01-28",
        "end_date": "2025-01-28",
        "start_time": "21:00",
        "end_time": "22:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Salsa On 2 & Cha Cha- Beginner Intermediate"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Ladies Team",
        "day_of_week": "Wednesday",
        "start_date": "2025-01-29",
        "end_date": "2025-01-29",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Ladies Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "class",
        "event_name": "Company Class",
        "day_of_week": "Wednesday",
        "start_date": "2025-01-29",
        "end_date": "2025-01-29",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Company Class"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Touring & Training Team",
        "day_of_week": "Wednesday",
        "start_date": "2025-01-29",
        "end_date": "2025-01-29",
        "start_time": "21:00",
        "end_time": "22:30",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Touring & Training Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "bachata, merengue",
        "url": "",
        "event_type": "rehearsal",
        "event_name": "Rehearsal- Bachata Team",
        "day_of_week": "Thursday",
        "start_date": "2025-01-30",
        "end_date": "2025-01-30",
        "start_time": "19:00",
        "end_time": "20:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Rehearsal- Bachata Team"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "bachata, merengue",
        "url": "",
        "event_type": "class",
        "event_name": "Bachata & Merengue- All Levels",
        "day_of_week": "Thursday",
        "start_date": "2025-01-30",
        "end_date": "2025-01-30",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Bachata & Merengue- All Levels"
    },
    {
        "org_name": "Studio 4 Athletics",
        "dance_style": "salsa",
        "url": "",
        "event_type": "social dance",
        "event_name": "Student Social & Practice Time",
        "day_of_week": "Thursday",
        "start_date": "2025-01-30",
        "end_date": "2025-01-30",
        "start_time": "20:00",
        "end_time": "21:00",
        "price": "",
        "location": "Studio 4 Athletics, 715 Yates St, Victoria, BC V8W 1L6, Canada",
        "description": "Student Social & Practice Time"
    }
]
"""

# Parse the JSON string into a Python list of dictionaries
data = json.loads(string)

# Convert the list of dictionaries into a pandas DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)
