name: Sync Environment Variables to Render

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
    paths:
      - 'src/.env'  # Only trigger when .env changes

jobs:
  sync-env-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync environment variables to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Syncing environment variables to Render..."

          # Read .env file and sync each variable to Render
          # Skips JSON file paths and comments
          while IFS= read -r line || [ -n "$line" ]; do
            # Skip empty lines and comments
            if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
              continue
            fi

            # Skip lines that contain JSON file paths (we handle those as Secret Files)
            if [[ "$line" =~ _PATH=.*\.json ]] || [[ "$line" =~ _auth\.json ]]; then
              echo "Skipping JSON path: $line"
              continue
            fi

            # Extract key and value
            key=$(echo "$line" | cut -d '=' -f 1)
            value=$(echo "$line" | cut -d '=' -f 2-)

            # Remove any surrounding quotes from value
            value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")

            echo "Setting $key in Render..."

            # Use Render API to set environment variable
            curl -X PUT \
              "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/env-vars/${key}" \
              -H "Authorization: Bearer ${RENDER_API_KEY}" \
              -H "Content-Type: application/json" \
              -d "{\"value\": \"${value}\"}" \
              || echo "Failed to set $key (might need to be created first)"

          done < src/.env

          echo "Environment sync complete!"

      - name: Trigger Render Deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering Render deployment to pick up new environment variables..."
          curl -X POST \
            "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": false}'
